### ISSUE TITLE
error when using ng-icons 22.2.0 with Angular 14.2.1

### ISSUE THREAD

**Issue by kokecar11** [ng-icons/ng-icons#41] opened 2022-09-30 16:34 UTC
**Describe the bug**

When I'm using modularization in angular and I use some icons from ng-icons/heroicons 22.2.0 I get this error 
**ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[InjectionToken Icons Token -> InjectionToken Icons Token -> InjectionToken Icons Token].**

I use a shared module, to use components in other modules of the application, in other previous versions this error did not happen to me.

**Packages:**
 - @ng-icons/core
 - Version [22.2.0]
 - @ng-icons/heroicons
 - Version [22.2.0]

**Comment by kokecar11** [comment] 2022-09-30 17:13
the solution for this error is to declare in the main module the icons and in the independent modules only declare the NgIcon module.

**Comment by ashley-hunter** [comment] 2022-09-30 17:15
Thank you for the feedback and letting me know the solution 😊

**Comment by ashley-hunter** [comment] 2022-10-04 20:45
I believe I was able to reproduce this issue and a fix should be available in 22.3.0 if that is of any help to you.

**Comment by gwesterman** [comment] 2022-11-07 10:35
Using version 22.4.0 I can still reproduce this bug. I'm applying the fix suggested by @kokecar11 for now but it's not optimal as one has to import all icons used by independent libraries, information that the main module should not know anything about.

**Comment by ashley-hunter** [comment] 2022-11-07 10:44
Thanks for reporting the issue @gwesterman, I will re-open this issue. Would you mind providing a reproduction environment so I can verify any fix, here is a stackblitz you could use to re-create the issue: https://stackblitz.com/edit/angular-ivy-jenhrr?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fshared%2Fshared.module.ts

Thanks!

**Comment by ashley-hunter** [comment] 2023-05-14 13:53
Closing as unable to reproduce. If this is still and issue, provide a reproduction environment and I'll be happy to investigate.

**Closed by ashley-hunter** 2023-05-14 13:53 UTC
Labels: need repro
