### ISSUE TITLE
Icons alignment wrong.

### ISSUE THREAD

**Issue by dailytabs** [ng-icons/ng-icons#116] opened 2024-06-27 21:39 UTC
Using:
```
@ng-bootstrap/ng-bootstrap": "^17.0.0",
@ng-icons/bootstrap-icons": "^28.0.0",
@ng-icons/core": "^28.0.0",
```

No custom SASS.

Icons, by default, are only showing their top half.

If I add:
```
ng-icon {
    @extend .d-inline;
}
```
They are closer to properly aligned, but not perfect.

**Comment by ashley-hunter** [comment] 2024-06-28 09:20
Thanks for the report, the issue is due to how bootstrap sets the vertical align property globally on all svg elements. I'll get a fix implemented later today. Thanks!

https://stackblitz.com/edit/stackblitz-starters-nr3x6k?file=src%2Fmain.ts

**Comment by ashley-hunter** [comment] 2024-06-28 20:34
The latest release should now resolve this issue. Any issues let me know.

**Comment by dailytabs** [comment] 2024-06-30 04:44
Had to take a break, came back and noticed that vertical-align seemed to be the culprit, then I remembered this issue! Updated and it is significantly better, but still seems to be cut off by 1 or 2 pixels.

https://stackblitz.com/edit/angular-uejkh6?file=src%2Fapp%2Fngbicontest.html

![image](https://github.com/ng-icons/ng-icons/assets/1219653/b7e38686-a35b-4bd8-ab1a-765415507e02)
Is this a Firefox thing?

**Comment by ashley-hunter** [comment] 2024-06-30 10:01
Its a strange one, no amount of tweaking the vertical align, line-height etc.. makes the icon and text align perfectly as far as I can see. The only thing that appears to work in all scenarios is to set `display: inline-flex` and `align-items: center` on the `.btn` class.

**Comment by ashley-hunter** [comment] 2024-08-16 20:49
Closing as I don't seem to find anyway to resolve this within the icon component itself. If you have any further suggestions we can re-open. Thanks.

**Closed by ashley-hunter** 2024-08-16 20:49 UTC
